# Generated by Django 3.1.4 on 2020-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[(1, 'waiting payment'), (2, 'payment confirmed'), (3, 'transaction complete'), (4, 'purchase cancelled')], default=1, max_length=20),
        ),
    ]
