# Generated by Django 3.1.4 on 2021-01-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210117_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='products',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='ecommerce.purchaseorder'),
        ),
    ]
